# -*- coding: utf-8 -*-
"""BajiClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMCfh_7ofoHSgAYpRAjzy42E_Zm5h2Uu

# Baji/Ru voice detection

**Dataset Building**

Train: https://drive.google.com/drive/folders/1moBQJ01A4QFr5iQsu51J2grdqOCYso3M

Test: https://drive.google.com/drive/folders/1pfGGShu_PkbUN90acLyI6esgb1twAFv6
"""

# import drive
from google.colab import drive
drive.mount('/content/drive')

"""## Audio Windowing"""

import librosa
import numpy as np

BAJI_PATH = "/content/drive/MyDrive/Voice Samples/Train/Baji Talking.wav"
LOWJI_PATH = "/content/drive/MyDrive/Voice Samples/Train/Lowji Talking.wav"

SR = 16000
WINDOW_SEC = 1.0
N_MSPEC = 20
N_WINDOWS = 2000
TOP_DB = 30  # increase if too much silence slips through, decrease if too much speech is cut

def sample_windows(audio_path, label, window_sec=WINDOW_SEC, sr=SR, n_mspec=N_MSPEC, n_windows=N_WINDOWS):
      print(f"Loading {audio_path}...")
      audio, _ = librosa.load(audio_path, sr=sr, mono=True)
      window_len = int(window_sec * sr)

      # Get non-silent intervals and concatenate them
      intervals = librosa.effects.split(audio, top_db=TOP_DB)
      speech_audio = np.concatenate([audio[start:end] for start, end in intervals])
      print(f"  Speech after silence removal: {len(speech_audio)/sr:.1f}s of {len(audio)/sr:.1f}s")
      #Randomly sample 2000 windows
      X, y = [], []
      for _ in range(n_windows):
          start = np.random.randint(0, len(speech_audio) - window_len)
          segment = speech_audio[start : start + window_len]
          mspec = librosa.feature.melspectrogram(y=segment, sr=sr)
          X.append(mspec[..., np.newaxis])
          y.append(label)
      print(f"  Done. Shape: {np.array(X).shape}")
      return np.array(X), np.array(y)
#extract mel-spectrogram from each chunk and converts it into 2D feature matrix
X_baji,  y_baji  = sample_windows(BAJI_PATH,  label=0)
X_lowji, y_lowji = sample_windows(LOWJI_PATH, label=1)

X = np.concatenate([X_baji,  X_lowji])
y = np.concatenate([y_baji, y_lowji])

print(f"Total dataset: {X.shape}, labels: {y.shape}")

# Test intervals

from IPython.display import Audio, display

# Baji
audio_baji, _ = librosa.load(BAJI_PATH, sr=SR, mono=True)
intervals_baji = librosa.effects.split(audio_baji, top_db=TOP_DB)
speech_baji = np.concatenate([audio_baji[start:end] for start, end in intervals_baji])
print(f"Baji — Original: {len(audio_baji)/SR:.1f}s | Speech: {len(speech_baji)/SR:.1f}s")
display(Audio(speech_baji, rate=SR))

# Lowji
audio_lowji, _ = librosa.load(LOWJI_PATH, sr=SR, mono=True)
intervals_lowji = librosa.effects.split(audio_lowji, top_db=TOP_DB)
speech_lowji = np.concatenate([audio_lowji[start:end] for start, end in intervals_lowji])
print(f"Lowji — Original: {len(audio_lowji)/SR:.1f}s | Speech: {len(speech_lowji)/SR:.1f}s")
display(Audio(speech_lowji, rate=SR))

#

import matplotlib.pyplot as plt
import librosa.display

plt.figure(figsize=(8, 4))
# Visualize the first Mel-Spectrogram from the batch
X_dB = librosa.power_to_db(X[0, :, :, 0], ref=np.max);
librosa.display.specshow(
    X_dB,
    x_axis="time",
    sr=SR
)
plt.colorbar()
plt.title("MSPEC")
plt.ylabel("MSPEC coefficient")
plt.xlabel("Time")
plt.tight_layout()
plt.show()

"""## CNN Train

"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping

"""Train/test split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,       # Here 25% of the data is used
    random_state=42,      # Changing this parameter will generate different sets of train/test
    shuffle=True,
    stratify=y,
)

print(f"Train: {X_train.shape} | Val: {X_test.shape}")

input_shape = X_train.shape[1:]

model = Sequential([
      # Conv2D scans the mspec "image" for local patterns (voice texture, formants)
      # 16 filters = 16 different patterns to detect
      # kernel (3,3) = each filter looks at a 3x3 patch at a time
      Conv2D(16, kernel_size=(3,3), activation='relu', input_shape=input_shape),

      # Downsamples by taking the max value in each 2x2 block
      # reduces computation and makes detected patterns more robust to small shifts
      MaxPooling2D(pool_size=(2,2)),

      # Converts the 2D feature map into a 1D vector so Dense layers can process it
      Flatten(),

      # Learns combinations of the CNN features that distinguish Baji from Lowji
      Dense(16, activation='relu'),

      # Single output neuron: 0 = Baji, 1 = Lowji
      # sigmoid squashes output to 0–1 so it can be treated as a probability
      Dense(1, activation='sigmoid')
  ])

# Adam handles learning rate automatically, good default optimizer
# binary_crossentropy is the standard loss for two-class problems
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# stops training when val_loss stops improving, restores best weights
early_stop = EarlyStopping(
      monitor='val_loss',
      patience=5,        # stops after 5 epochs of no improvement
      restore_best_weights=True
  )

history = model.fit(
      X_train, y_train,
      validation_data=(X_test, y_test),  # model never trains on val, only evaluates
      epochs=50,                        # same as WakeWord notebook
      batch_size = 4,                     # same as WakeWord notebook
      callbacks=[early_stop]
)

"""## CNN Test"""

import time
import os
os.listdir('/content/drive/MyDrive/Voice Samples/Test')

TEST_PATH = "/content/drive/MyDrive/Voice Samples/Test/Baji and Lowji.wav"
LABELS_TEST_PATH = "/content/drive/MyDrive/Voice Samples/Test/labels.txt"

# Load and remove silence
test_audio, _ = librosa.load(TEST_PATH, sr=SR, mono=True)
intervals = librosa.effects.split(test_audio, top_db=TOP_DB)
speech_test = np.concatenate([test_audio[start:end] for start, end in intervals])
print(f"Test clip — Original: {len(test_audio)/SR:.1f}s | Speech: {len(speech_test)/SR:.1f}s")

"""### Querying the model with the test audio
Note with the current testing setup windows could exist that are a mix of Baji and Ru

Refactoring to be truer to a stream of audio is a priority
"""

# Slide 1-second window with 50% overlap
window_len = int(WINDOW_SEC * SR)
hop_len = window_len // 2
predictions = []
timestamps = []
startTime = time.perf_counter()
print(f"start {startTime:0.4f}")
for start in range(0, len(test_audio) - window_len, hop_len):
      segment = test_audio[start : start + window_len]
      mspec = librosa.feature.melspectrogram(y=segment, sr=SR)
      mspec = mspec[np.newaxis, ..., np.newaxis]  # add batch and channel dims
      prob = model.predict(mspec, verbose=0)[0][0]
      predictions.append(prob)
      timestamps.append(start / SR)
endTime = time.perf_counter()
print(f"end {endTime:0.4f}")
print(f"completed test in {endTime - startTime:0.4f} seconds")
average = 1000*(endTime-startTime)/((len(test_audio) - window_len)/hop_len)
print(f"with an average of {average:0.4f} ms per prediction")

"""### Graphing the results of the query"""

predictions = np.array(predictions)
# 0 = Baji, 1 = Lowji
labels = (predictions > 0.5).astype(int)
print(f"Baji windows: {(labels==0).sum()} | Lowji windows: {(labels==1).sum()}")

plt.figure(figsize=(14, 3))
plt.plot(timestamps, predictions, alpha=0.5, linewidth=0.8)
plt.axhline(0.5, color='red', linestyle='--', label='threshold')
plt.yticks([0, 0.5, 1], ['Baji', 'threshold', 'Lowji'])
plt.xlabel("Time (s)")
plt.title("Speaker predictions over time")
plt.legend()
plt.tight_layout()
plt.show()

"""### Generating visual of the CNN's result for a snippet"""

import matplotlib.patches as mpatches

START_SEC = 0
END_SEC = 60

segment = test_audio[START_SEC*SR : END_SEC*SR]
display(Audio(segment, rate=SR))

mask = (np.array(timestamps) >= START_SEC) & (np.array(timestamps) < END_SEC)
window_times = np.array(timestamps)[mask]
window_labels = labels[mask]

fig, ax = plt.subplots(figsize=(14, 2))
for t, label in zip(window_times, window_labels):
      color = '#4C9BE8' if label == 0 else '#E8734C'
      ax.barh(0, WINDOW_SEC * 0.5, left=t, color=color, edgecolor='none', height=0.5)

baji_patch  = mpatches.Patch(color='#4C9BE8', label='Baji')
lowji_patch = mpatches.Patch(color='#E8734C', label='Lowji')
ax.legend(handles=[baji_patch, lowji_patch], loc='upper right')
ax.set_xlabel("Time (s)")
ax.set_xlim(START_SEC, END_SEC)
ax.set_xticks(range(START_SEC, END_SEC + 1, 1))
ax.set_yticks([])
ax.set_title("Speaker predictions (blue = Baji, orange = Lowji)")
plt.tight_layout()
plt.show()

"""### Generating accuracy statistic"""

correct_predictions = 0
total_predictions_considered = 0

with open(LABELS_TEST_PATH, 'r') as f:
    for line in f:
        parts = line.strip().split('\t')
        if len(parts) != 3:
            print(f"Warning: Skipping malformed line in Labels.txt: {line.strip()}")
            continue

        start_seg = float(parts[0])
        end_seg = float(parts[1])
        code = int(parts[2])

        ground_truth_label = None
        is_dont_care = False

        if code == 111: # Baji
            ground_truth_label = 0
        elif code == 211: # Lowji
            ground_truth_label = 1
        elif code == 133: # Baji breathing, don't really care if it gets it right
            ground_truth_label = 0
            is_dont_care = True
        elif code == 233: # Lowji breathing, same as above
            ground_truth_label = 1
            is_dont_care = True
        else:
            print(f"Warning: Unknown code {code} in Labels.txt. Skipping segment {start_seg}-{end_seg}.")
            continue

        # Iterate through all CNN predictions and their timestamps
        for i in range(len(timestamps)):
            cnn_timestamp = timestamps[i]
            cnn_predicted_label = labels[i]

            # Consider predictions whose start timestamp falls within the ground truth segment
            # if a prediction falls outside of a truth segment, truth is silence, so answer is irrelevent
            if start_seg <= cnn_timestamp < end_seg:
                if is_dont_care:
                    # If it's a 'don't care' code and CNN predicts correctly, count it.
                    # If CNN predicts incorrectly, it's ignored (neither correct nor incorrect).
                    if cnn_predicted_label == ground_truth_label:
                        correct_predictions += 1
                        total_predictions_considered += 1
                else: # Not a 'don't care' code (111 or 211)
                    total_predictions_considered += 1
                    if cnn_predicted_label == ground_truth_label:
                        correct_predictions += 1

# Calculate accuracy
if total_predictions_considered > 0:
    accuracy = (correct_predictions / total_predictions_considered) * 100
    print(f"\nAccuracy: {accuracy:.2f}% ({correct_predictions} correct out of {total_predictions_considered} considered predictions)")
else:
    print("\nNo relevant predictions found within the labeled segments in Labels.txt to calculate accuracy.")